### ISSUE TITLE
Addition of Boosting algorithms ⚡

### ISSUE THREAD

**Issue by BlueBlaze6335** [gdscjgec/ML-Gallery#1]
## 🚀 Add Boosting Algorithms to the Wine quality testing notebook in [**Classification**](https://github.com/gdscjgec/ML-Gallery/tree/main/Classification) Directory

**Only five classification Algorithms are present. Add boosting algorithms , eg. XGboost, LGBM, etc.**

Often Boosting algorithms give better results. So try implementing those to get a better result than the present one. Then ***update the readme*** with the results and model !! Also add  brief description of the algorithm in the markdown cells of your notebook. Please use proper variable names and make the code readable with comments !!

**Additional**
You can add any other Algorithm  or you can also add Plots for more data analysis !

**Comment by void-02** [comment]
Hello,
I am willing to contribute to this issue.

**Comment by khusheekapoor** [comment]
I would like to solve this issue using R language. Please assign it to me. Thank you!

**Comment by BlueBlaze6335** [comment]
@void-02 i am assigning you this issue !! Clone the repo and start working ✌️.

**Comment by niloysikdar** [comment]
Assigned @khusheekapoor in R lang. All the best

**Comment by TishaJhabak1014** [comment]
@niloysikdar  Can I add another boosting model like adaboost or plz let me contribute ensemble modeling techniques like random forest. I can contribute both with doc. and code.

**Comment by niloysikdar** [comment]
@BlueBlaze6335 @anubhab1710 @sagnik1511

**Comment by BlueBlaze6335** [comment]
@TishaJhabak1014 yes you can add adaboost and other boosting algorithms. I have already used Random Forest , but there are many algorithms and you can try them too   !! I am assigning you and all the best !!

**Comment by sagnik1511** [comment]
> @niloysikdar Can I add another boosting model like adaboost or plz let me contribute ensemble modeling techniques like random forest. I can contribute both with doc. and code.

Yes, you can do for sure. But remember to create a seperate notebook for that. Happy contributing!

**Comment by TishaJhabak1014** [comment]
@sagnik1511 Can I make a readme where I will provide the link to the notebook with the implementation or should I combine the documentation and the code in a single notebook, Also, can I work on any dataset of my choice. Give some guidelines, please.

**Comment by BlueBlaze6335** [comment]
@TishaJhabak1014 you can download the notebook and add to the directory , and also provide the link to the notebook in the readme. And you can also work on any classification dataset but for that I will add another issue.

**Comment by TishaJhabak1014** [comment]
> @TishaJhabak1014 you can download the notebook and add it to the directory, and also provide the link to the notebook in the readme. And you can also work on any classification dataset but for that, I will add another issue.

Which notebook to download, is it the starter_nootbook.ipynb?. Also, I would like to create a readme and provide the link to the implementation notebook on it. Will be using a different dataset.

**Comment by BlueBlaze6335** [comment]
@TishaJhabak1014  check this [issue](https://github.com/gdscjgec/ML-Gallery/issues/5#issue-1014298335) !! You dont have to download any notebook , if you want to work on any new dataset. Otherwise , if you are thinking of enhancing [this](https://github.com/gdscjgec/ML-Gallery/tree/main/Classification) , then you can start right away and update the README with your enhancements.

**Comment by TishaJhabak1014** [comment]
> @TishaJhabak1014 check this [issue](https://github.com/gdscjgec/ML-Gallery/issues/5#issue-1014298335) !! You dont have to download any notebook , if you want to work on any new dataset. Otherwise , if you are thinking of enhancing [this](https://github.com/gdscjgec/ML-Gallery/tree/main/Classification) , then you can start right away and update the README with your enhancements.

Okay, so this issue deals with the wine dataset, Sure I can go for this issue first. Will contribute through the notebook. Update the main readme with developments. Thank you for the guidance.

**Comment by BlueBlaze6335** [comment]
@TishaJhabak1014 i am assigning you to this issue. Later you can contribute to the other mentioned above if you want to !! Happy contributing !!

**Comment by sagnik1511** [comment]
> @sagnik1511 Can I make a readme where I will provide the link to the notebook with the implementation or should I combine the documentation and the code in a single notebook, Also, can I work on any dataset of my choice. Give some guidelines, please.

After creating the notebook update [classification/README.md](https://github.com/gdscjgec/ML-Gallery/blob/main/Classification/README.md), not the main one. Happy contributing!!!

**Comment by TishaJhabak1014** [comment]
> > @sagnik1511 Can I make a readme where I will provide the link to the notebook with the implementation or should I combine the documentation and the code in a single notebook, Also, can I work on any dataset of my choice. Give some guidelines, please.
> 
> After creating the notebook update [classification/README.md](https://github.com/gdscjgec/ML-Gallery/blob/main/Classification/README.md), not the main one. Happy contributing!!!

@sagnik1511 One little doubt😅, I will update the readme with my improvements, but should I need to add the notebook in the `classification` directory??

**Comment by BlueBlaze6335** [comment]
@TishaJhabak1014 if you are working on the wine dataset , then update the same notebook , or add another one. But if some other dataset then create a new directory !! I think it's clear !!

**Comment by TishaJhabak1014** [comment]
> @TishaJhabak1014 if you are working on the wine dataset , then update the same notebook , or add another one. But if some other dataset then create a new directory !! I think it's clear !!

Okay, worked on the same dataset, may a add new notebook.

**Comment by void-02** [comment]
Hey @BlueBlaze6335 
Below are the accuracies which I got on implementing different boosting algorithms.
Should I make a new PR?
|Classifier|Accuracy|
| :--: | :--: |
|Adaboost|78.02%|
|XGBoost|93.33%|
|Light GBM|94.07%|
|Catboost|93.58%|
|Bagged XGBoost|93.58%|
|Bagged Light GBM|94.07%|
|Bagged Catboost |93.82%|
|Bagged Adaboost|88.39%|

**Comment by BlueBlaze6335** [comment]
@void-02 Definitely you can add these , but you should add them and compare to the existing results !! Then submit a PR. I will review and if you need any changes i will inform you.
