### ISSUE TITLE
Hyper-Parameter Tuning for Titanic Disaster models

### ISSUE THREAD

**Issue by avishkakavindu** [gdscjgec/ML-Gallery#45]
## 🚀 Hyper - Parameter Tuning for Titanic Disaster models

**A clear and concise description of what the feature is.**
I would like to work on Hyperparameter tuning of the models that are created for the Titanic dataset.

**Is your feature request related to a problem? Please describe.**
The models aren't tuned and due to that, the best result cannot be observed and can generalize the models.

**Describe the solution you'd like**
Tune models using GridSearchCV or 

**Describe alternatives you've considered**
Can use RandomSearch instead of GridSearch

**Additional context**
N/A

**Comment by avishkakavindu** [comment]
Still got the artificial neural network to tune which is tedious. So are we gonna cover that in the starter notebook ?

**Comment by BlueBlaze6335** [comment]
@avishkakavindu I think there is no need to do so , because the model might tend to overfit. That's all for now. You did a great job !!
