### ISSUE TITLE
Add a Classification project  !!

### ISSUE THREAD

**Issue by BlueBlaze6335** [gdscjgec/ML-Gallery#5]
### Choose your dataset from [here](https://github.com/gdscjgec/ML-Gallery/blob/main/Datasets.md)** or use any other dataset of your choice.

After downloading the dataset , you can work on that in an ide or a notebook. Solve the problem with proper EDA and data engineering. Use any classification algorithm you think is cool and submit a **README.md** file with the brief documentation of your project along with the ***.py/.ipynb*** file. 

***You can work on other dataset that is not mentioned  [here](https://github.com/gdscjgec/ML-Gallery/blob/main/Datasets.md)
but dont forget to add it to  [this](https://github.com/gdscjgec/ML-Gallery/blob/main/Datasets.md).***

**Comment by varun290101** [comment]
Can I work on this?

**Comment by BlueBlaze6335** [comment]
@varun290101 yes you can work on this issue. Work on any dataset apart from those which are already done !! And please provide proper documentation in the notebook and also a README. For example you can check [this](https://github.com/gdscjgec/ML-Gallery/tree/main/Classification). Please add another directory stating the dataset - Classification-[Dataset]

**Comment by varun290101** [comment]
I have done one on the titanic dataset maam, I don't think its been done by anyone. Can I add a readme.md file and push the same?

**Comment by BlueBlaze6335** [comment]
First of all , I am not Ma'am bro🥲 ! I have a request ,l please go through the repo properly !! [This](https://github.com/gdscjgec/ML-Gallery/blob/main/Starter_Notebook.ipynb) starter notebook is on the Titanic Dataset, So please work on any other dataset otherwise work on the other issue !!

**Comment by varun290101** [comment]
Oh i am sorry, sure thanks :)

**Comment by BlueBlaze6335** [comment]
@Kasrazeba-Mulla assigning you !! Follow the rules and then make PR !!

**Comment by Kasrazeba-Mulla** [comment]
@BlueBlaze6335 yes working on it :)

**Comment by Kasrazeba-Mulla** [comment]
@BlueBlaze6335 i have added  my contribution pls check ☑

**Comment by somyagr** [comment]
Please assign this issue to me, I'll work on Breast Cancer Wisconsin (Diagnostic) Data Set.

**Comment by BlueBlaze6335** [comment]
@somyagr 🤟🏻!!

**Comment by devanshigarg01** [comment]
Please assign me this issue, I will be working on heart disease dataset

**Comment by puranjay123** [comment]
@BlueBlaze6335  Please assign me this issue.

**Comment by BlueBlaze6335** [comment]
@puranjay123 this issue will be closed as there are abundant solutions !! Work on the other one that I have assigned to you !
