### ISSUE TITLE
Data imputation methods

### ISSUE THREAD

**Issue by avishkakavindu** [gdscjgec/ML-Gallery#51]
## 🚀 Feature

**A clear and concise description of what the feature is.**
I like to work on data imputation methods and their impact on model performance. 

**Is your feature request related to a problem? Please describe.**
I think it will be better to do with this with a beginner-friendly dataset that already has experience(ex, titanic dataset)

**Describe the solution you'd like**
- Mean/Median imputation
- Most frequent value
- knn and deep learning

**Comment by BlueBlaze6335** [comment]
@avishkakavindu Go ahead !!
