### ISSUE TITLE
House price prediction

### ISSUE THREAD

**Issue by AshiJoshi** [gdscjgec/ML-Gallery#57]
## 🚀 Feature

**I would like to add code for house price prediction**

**Is your feature request related to a problem? Please describe.**
It will provide insights into various regression algorithms and differences comparisons of their performances

**Describe the solution you'd like**
I will make use of regression algorithms like linear regression, ridge regression, PCA regression.

**Comment by BlueBlaze6335** [comment]
@AshiJoshi there is no need to create a separate issue !! Check this out https://github.com/gdscjgec/ML-Gallery/issues/2#issue-1013097261 !!

**Comment by BlueBlaze6335** [comment]
@AshiJoshi a project is already done on the house prediction !! I dont think doing the same is necessary !
